### ISSUE TITLE
about the "paintings/"

### ISSUE THREAD

**Issue by Fengxuxu** [Bekyilma/MRL_VA_RecSys#1]
![image](https://github.com/Bekyilma/MRL_VA_RecSys/assets/132980800/9513dcf8-c52b-4cb4-a42c-674a6f6959ff)
I can't find the file 'paintings' at all, could you please provide this document to us? Thanks!

**Comment by Bekyilma** [comment]
Hi @Fengxuxu ,

You need to download the dataset here: https://project-banana.eu/va-recsys/appdata.zip, extract it and place the 'paintings/'  in your working directory.

Please follow the instructions in the README https://github.com/Bekyilma/MRL_VA_RecSys/blob/main/RecSys_engines/README.md

**Comment by Fengxuxu** [comment]
Thanks again!
